services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./frontend/data:/app/data
      - ./api/api_keys.json:/app/api_keys.json

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  uploads:
  data:
