name: Deploy API to GHCR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest

      - name: Create Release
        if: success()
        run: |
          pip install PyGithub
          python api/github_actions.py \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --repo-name ${{ github.repository }} \
            --tag-name "api-v${{ github.run_number }}" \
            --release-name "API Release v${{ github.run_number }}" \
            --body "API Docker image deployed to GHCR"
